### PR TITLE
Add NetStandard project

### PR DESCRIPTION
**Pull request by Dykam**

### CODE REVIEW

**Comment by stevenlivz** [comment]
I have moved this project to .NET Core 2 due to various compatibility issues i was running into with the latest Xamarin releases. Thanks for the pr.

**Comment by Dykam** [comment]
The reason for netstandard is that netcore is not build-compatible  with e.g. Unity, our use case. And I thought it was the same for Xamarin, but I suppose that's not the case. You can target multiple platforms at the same time, btw, using TargetFramework**s**, e.g. `<TargetFrameworks>netstandard2.0;netcoreapp2.0</TargetFrameworks>`.

**Comment by stevenlivz** [comment]
I think i may branch it ... i had (wrongly) assumed Core would make it easier ... it does in some cases and causes chaos in others :-)

**Comment by Dykam** [comment]
From my experience single-source-code isn't very difficult, I'm working on
a fairly complicated project which cross-targets net461 and netstandard.
Branching it probably more work in the long run.

Unrelated, me and some others on my team added a bunch of other changes for
a project we worked on, including a fairly important xml-escape bug:
https://github.com/Dykam/XMPPEngineer/commits/hoppa You might want to just
cherry-pick the relevant commits, as some where for our project
specifically.


--
Mark

**Comment by stevenlivz** [comment]
Thanks. Will try the multi-platform option. I tried using the core in a Xamarin forms app but it also uses a package that works with different versions of .Net and it's proving a pain to figure it out. Will look at your updates - thx.

**Comment by stevenlivz** [comment]
Thanks - i merged this in to target both frameworks. Also resolved the conflicts that appeared. Will pull in the other bits you mention.

**Pull request closed without merging**
